language: node_js
node_js:
  - "4.0.0"
before_script:
  - npm install -g npm
script: "npm run coveralls"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | node_modules/.bin/coveralls"
